[workspace]
authors = ["Tobias Hunger <tobias@prefix.dev>"]
channels = ["https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge"]
name = "code"
platforms = ["linux-64"]
preview = ["pixi-build"]
version = "0.1.0"

[activation.env]
GLIBC_TUNABLES = "glibc.rtld.execstack=2"
TURTLEBOT3_MODEL = "burger"

[tasks]
simulation = "ros2 launch turtlebot3_mogi simulation_bringup_line_follow.launch.py"
line-follower = "ros2 run turtlebot3_mogi_py line_follower_cnn"

[dependencies]
ros-jazzy-turtlebot3-mogi = { path = "turtlebot3_mogi" }
ros-jazzy-turtlebot3-mogi-py = { path = "turtlebot3_mogi_py" }
ros-jazzy-mogi-trajectory-server = { path = "mogi_trajectory_server" }
ros-jazzy-turtlebot3-gazebo = { path = "turtlebot3_gazebo" }
ros-jazzy-turtlebot3 = ">=2.3.6,<3"
ros-jazzy-turtlebot3-msgs = ">=2.4.0,<3"
ros-jazzy-turtlebot3-simulations = ">=2.3.7,<3"
ros-jazzy-ros-gz = ">=1.0.19,<2"
ros-jazzy-cv-bridge = ">=4.1.0,<5"
ros-jazzy-rviz2 = ">=14.1.19,<15"
ros-jazzy-ros2launch = ">=0.26.11,<0.27"
ros-jazzy-ros2run = ">=0.32.8,<0.33"
tensorflow = ">=2.19.1,<3"
py-opencv = ">=4.12.0,<5"
scikit-learn = ">=1.9.0,<2"
imutils = ">=0.5.4,<0.6"
matplotlib-base = ">=3.10.9,<4"
h5py = ">=3.16.0,<4"
keras = "==3.7.0"
